// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_STCBROADMESSAGETEST_BROADFLAT_H_
#define FLATBUFFERS_GENERATED_STCBROADMESSAGETEST_BROADFLAT_H_

#include "flatbuffers/flatbuffers.h"


namespace BroadFlat {

struct StcBroadMessageTest;

struct StcBroadMessageTest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_NAME = 6,
    VT_AGE = 8
  };
  uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  uint32_t age() const { return GetField<uint32_t>(VT_AGE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<uint32_t>(verifier, VT_AGE) &&
           verifier.EndTable();
  }
};

struct StcBroadMessageTestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) { fbb_.AddElement<uint32_t>(StcBroadMessageTest::VT_ID, id, 0); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(StcBroadMessageTest::VT_NAME, name); }
  void add_age(uint32_t age) { fbb_.AddElement<uint32_t>(StcBroadMessageTest::VT_AGE, age, 0); }
  StcBroadMessageTestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  StcBroadMessageTestBuilder &operator=(const StcBroadMessageTestBuilder &);
  flatbuffers::Offset<StcBroadMessageTest> Finish() {
    auto o = flatbuffers::Offset<StcBroadMessageTest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<StcBroadMessageTest> CreateStcBroadMessageTest(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t id = 0,
   flatbuffers::Offset<flatbuffers::String> name = 0,
   uint32_t age = 0) {
  StcBroadMessageTestBuilder builder_(_fbb);
  builder_.add_age(age);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const BroadFlat::StcBroadMessageTest *GetStcBroadMessageTest(const void *buf) { return flatbuffers::GetRoot<BroadFlat::StcBroadMessageTest>(buf); }

inline bool VerifyStcBroadMessageTestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<BroadFlat::StcBroadMessageTest>(); }

inline void FinishStcBroadMessageTestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<BroadFlat::StcBroadMessageTest> root) { fbb.Finish(root); }

}  // namespace BroadFlat

#endif  // FLATBUFFERS_GENERATED_STCBROADMESSAGETEST_BROADFLAT_H_
